name: Build Utaformatix With Electron
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
          - runs-on: macos-latest
            arch: osx-x64
          - runs-on: ubuntu-latest
            arch: linux-x64
          - runs-on: macos-latest
            arch: osx-arm64
          - runs-on: ubuntu-latest
            arch: linux-arm64

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          ref: master

      - name: Get Date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYYMMDD"

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build master branch
        run: ./gradlew build

      - name: Build Harmoloid
        run: |
          git clone https://github.com/sdercolin/harmoloid2
          cd harmoloid2
          ./gradlew build
          mkdir ../build/distributions/harm
          cp -r build/distributions/* ../build/distributions/harm

      - name: Get ToPinyinAndRomaji
        run: |
          cd ./build/distributions/
          git clone https://github.com/atonyxu/ToPinyinAndRomaji

      - name: Get LRC-Maker
        run: |
          cd ./build/distributions/
          git clone https://github.com/magic-akari/lrc-maker -b gh-pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build/distributions"

      - name: Run electron-package
        run: |
          npm i electron-packager -g
          cp ./package.json ./build/distributions/package.json
          cp ./main.js ./build/distributions/main.js
          npm run package

      - name: compress package
        run: 7z a utaformatix-${{ matrix.os.arch }}.zip ./utaformatix-electron/*

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: utaformatix-${{ matrix.os.arch }}.zip
          path: utaformatix-${{ matrix.os.arch }}.zip

      - name: Create release 
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.time }}
          body: utaformatix build on ${{ steps.date.outputs.time }}
          files: |
            utaformatix-${{ matrix.os.arch }}.zip
