name: Build Utaformatix With Electron
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
          - runs-on: macos-latest
            arch: osx-x64
          - runs-on: ubuntu-latest
            arch: linux-x64
          - runs-on: macos-latest
            arch: osx-arm64
          - runs-on: ubuntu-latest
            arch: linux-arm64

    steps:
      - name: Get Date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYYMMDD"

      - name: Move File
        run: git clone https://github.com/atonyxu/utaformatix3-electron

      - name: Build Cache Restore
        uses: actions/cache/restore@v3
        with:
          path: |
            ./utaformatix3-electron/build/distributions/
          key: utaformatix-${{ steps.date.outputs.time }}-${{ matrix.os.arch }}

      - name: Run electron-package
        run: |
          npm i electron-packager -g
          cp ./utaformatix3-electron/package.json ./utaformatix3-electron/build/distributions/package.json
          cp ./utaformatix3-electron/main.js ./utaformatix3-electron/build/distributions/main.js
          cp ./utaformatix3-electron/package.json ./package.json
          cp ./utaformatix3-electron/main.js ./main.js
          npm run package

      - name: compress package
        run: 7z a utaformatix-${{ matrix.os.arch }}.zip ./utaformatix-electron/*

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: utaformatix-${{ matrix.os.arch }}.zip
          path: utaformatix-${{ matrix.os.arch }}.zip

      - name: Create release 
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.time }}
          body: utaformatix build on ${{ steps.date.outputs.time }}
          files: |
            utaformatix-${{ matrix.os.arch }}.zip
